Feature/01 html
Johnbedoya1426/Pokedex pull request #3
Opened 2023-03-09 15:03 UTC by Johnbedoya1426

completing layout

2023-03-09 15:44 UTC, lopezquekk commented
Falta detalle del PR adjuntar videos y descripcion de lo que hace

2023-03-09 15:48 UTC, lopezquekk requested changes

2023-03-09 15:48 UTC, lopezquekk commented on cardInformation.html
> +<html lang="en" id="card-information">
porque este ID?

2023-03-09 15:48 UTC, lopezquekk commented on cardInformation.html
> +    <meta charset="UTF-8">
Todas las etiquetas se deben cerrar

2023-03-09 15:48 UTC, lopezquekk commented on cardInformation.html
> +<!DOCTYPE html>
El nombre del documento no es descriptivo, que hace?

2023-03-09 15:48 UTC, lopezquekk commented on cardInformation.html
> +                <div class="height-information">
Porque las clases son tan especificas?, se pueden hacer reusables

2023-03-09 15:48 UTC, lopezquekk commented on cardInformation.html
> +                <img src="./assets/Divider.svg" alt="divider">
El divider se debe hacer con CSS

2023-03-09 15:48 UTC, lopezquekk commented on cardInformation.html
> +                        <img src="./assets/VectorHeight.svg" alt="altura">
Con CSS

2023-03-09 15:48 UTC, lopezquekk commented on cardInformation.html
> +                    <p>Ability 1</p>
Esto no se podria hacer dinamico

2023-03-09 15:55 UTC, Johnbedoya1426 commented on cardInformation.html
> +    <meta charset="UTF-8">
la etiqueta cierra abajo antes de cerrar el documento

2023-03-09 15:56 UTC, lopezquekk requested changes

2023-03-09 15:56 UTC, lopezquekk commented on cardInformation.html
> +                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
no deberia existir saltos de linea en HTML

2023-03-09 15:56 UTC, lopezquekk commented on cardInformation.html
> +                    <h3 class="stat-hp">HP</h3>
Clases especificas que no se pueden volver dinamicas, cambiar esto

2023-03-09 15:56 UTC, lopezquekk commented on cardInformation.html
> +                    <img src="./assets/DividerLarge.svg" alt="divider">
Ningun Divider debe ser una image

2023-03-09 15:56 UTC, lopezquekk commented on index.html
> +                <button class="search-button">
Button no deberia cubrir el input

2023-03-09 15:56 UTC, lopezquekk commented on index.html
> +                <figure class="container-img">
Porque es figure?

2023-03-09 15:56 UTC, lopezquekk commented on index.html
> +                    <img src="./assets/imagePokemon.svg" alt="img">
Hya imagenes en mayusculas iniciales y en minusculas iniciales, unificar el formato, preferiblemente, minusculas  ya que no son componentes

2023-03-09 15:56 UTC, lopezquekk commented on style.css
> +* {
Que reseter usaste?, debe ser uno mas riguroso para que sea compatible con otros navegadores

2023-03-09 15:56 UTC, lopezquekk commented on style.css
> +    left: 0.51%;
cambiar CSS a rem o un manejo mejor de proporciones, no usar posiciones con porcentajes

2023-03-09 15:56 UTC, lopezquekk commented on style.css
> +    margin-left: 1.2rem;
Combinando rem con px puede ser una mala practica, unificar

2023-03-09 16:03 UTC, lopezquekk commented
Fuentes no se ven bien
Espaciado está mal no llena la vista completa
La vista de detalle está mal

<img width="600" alt="Screenshot 2023-03-09 at 11 00 59 AM" src="https://user-images.githubusercontent.com/2974179/224081753-77f9fe3c-00e5-4ea5-bad3-b3cc06aeb4a6.png">
<img width="600" alt="Screenshot 2023-03-09 at 11 00 09 AM" src="https://user-images.githubusercontent.com/2974179/224081763-45e6a1b3-c394-4a30-8f96-4870230c3145.png">

2023-03-09 16:13 UTC, lopezquekk commented on cardInformation.html
> +    <meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    
    Ninguna de estas lo hace

2023-03-09 16:15 UTC, Johnbedoya1426 commented on index.html
> +                    <img src="./assets/imagePokemon.svg" alt="img">
arreglado

2023-03-09 16:16 UTC, Johnbedoya1426 commented on index.html
> +                <figure class="container-img">
Un contenedor para que contenga la imagen y se pueda manipular

2023-03-09 16:29 UTC, Johnbedoya1426 commented on cardInformation.html
> +                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
arreglado

2023-03-09 19:40 UTC, Johnbedoya1426 commented on style.css
> +    left: 0.51%;
arreglado

2023-03-09 19:40 UTC, Johnbedoya1426 commented on index.html
> +                <button class="search-button">
arreglado

2023-03-09 20:56 UTC, Johnbedoya1426 commented on cardInformation.html
> +                <img src="./assets/Divider.svg" alt="divider">
arreglado

2023-03-09 20:56 UTC, Johnbedoya1426 commented on cardInformation.html
> +                        <img src="./assets/VectorHeight.svg" alt="altura">
arreglado

2023-03-09 20:56 UTC, Johnbedoya1426 commented on cardInformation.html
> +                    <p>Ability 1</p>
arreglado

2023-03-09 20:56 UTC, Johnbedoya1426 commented on cardInformation.html
> +                    <img src="./assets/DividerLarge.svg" alt="divider">
arreglado

2023-03-09 20:57 UTC, Johnbedoya1426 commented on cardInformation.html
> +                    <h3 class="stat-hp">HP</h3>
arreglado

2023-03-09 22:19 UTC, Johnbedoya1426 commented on style.css
> +* {
arreglado

2023-03-09 23:16 UTC, Johnbedoya1426 commented
![This is an image](
![Screenshot 2023-03-09 at 5 47 56 PM](https://user-images.githubusercontent.com/108825873/224182086-e3eff58e-1c3c-4ff4-a266-594825316b81.png)
![Screenshot 2023-03-09 at 5 48 10 PM](https://user-images.githubusercontent.com/108825873/224182092-1f3541e4-029a-41dc-97aa-f42ddb7b340c.png)
![Screenshot 2023-03-09 at 5 48 33 PM](https://user-images.githubusercontent.com/108825873/224182099-309443c9-942c-4a20-a543-652444148c1d.png)
![Screenshot 2023-03-09 at 5 48 46 PM](https://user-images.githubusercontent.com/108825873/224182102-9f73985d-de2d-4627-9e1f-8d13e94968af.png)
![Screenshot 2023-03-09 at 5 51 20 PM](https://user-images.githubusercontent.com/108825873/224182105-3ec01e95-b5ad-4afd-b10d-4dbb3d492cca.png)
![Screenshot 2023-03-09 at 5 47 45 PM](https://user-images.githubusercontent.com/108825873/224182080-ff549f38-3e00-4e02-8624-e23cad544357.png)

2023-03-12 23:16 UTC, lopezquekk approved these changes

2023-03-12 23:17 UTC, lopezquekk approved these changes

2023-03-17 16:51 UTC, Johnbedoya1426 commented on cardInformation.html
> +    <meta charset="UTF-8">
HTML5 no permite el uso de etiquetas auto-cerradas
HTML5 y los diferentes navegadores tienen una gran capacidad para adaptarse a errores de sintaxis en el código, pero eso no significa que sea código válido.

2023-03-17 16:55 UTC, merged